I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 2296, in script
    i "Joana Olympios, ..."
  File "game/script.rpy", line 2296, in <module>
    i "Joana Olympios, ..."
NameError: name 'question_2_lindsey' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 2296, in script
    i "Joana Olympios, ..."
  File "D:\Aulas\AULAS ANO 4 SEGUNDO SEMESTRE\Projetos de Hardware para FPGAs\renpy-8.0.3-sdk\renpy\ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "D:\Aulas\AULAS ANO 4 SEGUNDO SEMESTRE\Projetos de Hardware para FPGAs\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\Aulas\AULAS ANO 4 SEGUNDO SEMESTRE\Projetos de Hardware para FPGAs\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 2296, in <module>
    i "Joana Olympios, ..."
NameError: name 'question_2_lindsey' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Questoes Questionaveis 1.0
Thu Feb  9 01:43:23 2023
